{
 "title": "Data Source Volume",
 "description": "Volume for each Grafana Data Source",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Data Source Volume\n\nThis is a test yall, dashboard outlines the volume of data being sent for each data source, where possible. It shows the following:\n\n* **Loki** - the number of log entries recorded\n* **Prometheus** - the number of metrics samples received by AMP for each Kubernetes cluster\n* **MySQL** - the volume of data currently tracked in the database\n* **New Relic** - the count of data for the New Relic account\n* **Infinity** - a liveliness of the underlying EAX service being accessed by the Infinity data source\n* **Opensearch / ElasticSearch** - the count of data being sent to the index\n* **Cloudwatch** - the volume of Cloudwatch data being sent to the AWS account"
   }
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Yardmaster Loki",
   "type": "timeseries",
   "description": "Total number of log lines on eax-vpc-prod-k8s-default",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({cluster_name=\"eax-vpc-prod-k8s-default\"} [5m]))",
     "legendFormat": "number of log entries"
    }
   ]
  },
  {
   "title": "EAX Prometheus | eax-infra | 470694524926",
   "type": "timeseries",
   "description": "total number of samples appended to the TSDB (Time Series Database) head",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL | gradual-rollout dev | prod-backend-413-rds.c6bpunvkeo75.us-east-1.rds.amazonaws.com",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "dev",
       "rawSql": "SELECT\n  NOW() AS time,\n  ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS data_volume_mb\nFROM\n  information_schema.tables\nWHERE\n  table_schema = 'dev'\nGROUP BY\n  time\nORDER BY\n  time;"
      }
     ]
    },
    {
     "title": "MySQL | gradual-rollout prod | prod-backend-416-rds-cluster.cluster-ro-c6bpunvkeo75.us-east-1.rds.amazonaws.com",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "prod",
       "rawSql": "SELECT\n  NOW() AS time,\n  ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS data_volume_mb\nFROM\n  information_schema.tables\nWHERE\n  table_schema = 'prod'\nGROUP BY\n  time\nORDER BY\n  time;"
      }
     ]
    },
    {
     "title": "MySQL | juno_error_reporter | jj1nad4ggdmntze.cpapbtjh5wgm.us-east-1.rds.amazonaws.com",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "juno_error_reporter",
       "rawSql": "SELECT\n  NOW() AS time,\n  ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS data_volume_mb\nFROM\n  information_schema.tables\nWHERE\n  table_schema = 'juno_error_reporter'\nGROUP BY\n  time\nORDER BY\n  time;"
      }
     ]
    },
    {
     "title": "MySQL | Pyramid Prod",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "performance_schema",
       "rawSql": "SELECT\n  NOW() AS time,\n  ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) AS data_volume_mb\nFROM\n  information_schema.tables\nWHERE\n  table_schema = 'pyramid_prod'\nGROUP BY\n  time\nORDER BY\n  time;"
      }
     ]
    }
   ]
  },
  {
   "title": "New Relic eks-kaboose-customer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of K8sClusterSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sClusterSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3819 },
     "targets": [
      {
       "expr": "nr_k8s_cluster_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total Infrastructure Events",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM InfrastructureEvent SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3819 },
     "targets": [
      {
       "expr": "nr_infrastructure_event_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sPodSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sPodSample SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_k8s_pod_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sContainerSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sContainerSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_k8s_container_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sNodeSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sNodeSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4123 },
     "targets": [
      {
       "expr": "nr_k8s_node_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total APM Transaction Events",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM Transaction SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_apm_transaction_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total Browser Events",
     "type": "timeseries",
     "description": "SELECT count(*) FROM AjaxRequest, BrowserInteraction, PageAction, PageView, PageViewTiming, BrowserTiming, JavaScriptError SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_browser_event_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-customer\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "New Relic eks-kaboose-platform",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of K8sClusterSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sClusterSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 692 },
     "targets": [
      {
       "expr": "nr_k8s_cluster_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total Infrastructure Events",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM InfrastructureEvent SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 692 },
     "targets": [
      {
       "expr": "nr_infrastructure_event_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sPodSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sPodSample SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 700 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_k8s_pod_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sContainerSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sContainerSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 700 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_k8s_container_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of K8sNodeSample",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM K8sNodeSample SINCE 1 minute ago",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 708 },
     "targets": [
      {
       "expr": "nr_k8s_node_sample_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total APM Transaction Events",
     "type": "timeseries",
     "description": "Returns results for the following NR query:\nSELECT count(*) FROM Transaction SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 708 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_apm_transaction_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Count of Total Browser Events",
     "type": "timeseries",
     "description": "SELECT count(*) FROM AjaxRequest, BrowserInteraction, PageAction, PageView, PageViewTiming, BrowserTiming, JavaScriptError SINCE 1 MINUTE AGO",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 716 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nr_browser_event_count{job=\"newrelic-metrics-exporter\",cluster=\"eks-kaboose-platform\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Infinity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infinity | service-aggregation-layer-prod",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "targets": [
      {
       "parser": "simple",
       "source": "url",
       "type": "graphql",
       "url": "https://service-aggregation-layer-prod.eax.ea.com/graphql",
       "url_options": {
        "body_content_type": "application/json",
        "body_graphql_query": "query PingQuery { \n  __typename\n}",
        "body_type": "graphql",
        "columns": [
         { "text": "timestamp", "type": "time" },
         { "text": "volume", "type": "number" }
        ],
        "data": "",
        "method": "POST",
        "params": [],
        "root_selector": "data.dataVolume"
       }
      }
     ]
    },
    {
     "title": "Infinity | Game Content Service Int",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "targets": [
      {
       "source": "url",
       "type": "json",
       "url": "https://sal-game-content-service-integration.eax.ea.com/_status/health",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Infinity | Game Content Service Prod",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "targets": [
      {
       "source": "url",
       "type": "json",
       "url": "https://sal-game-content-service-prod.eax.ea.com/_status/health",
       "url_options": { "data": "", "method": "GET" }
      }
     ]
    },
    {
     "title": "Infinity | JunoWeb Orchestrator Canaries  | https://juno-web-deploy-orchestrator-prod.eax.ea.com",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "targets": [
      { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
     ]
    },
    {
     "title": "Infinity | Juno Web Orchestrator Canaries V2",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
     "targets": [
      { "source": "url", "type": "json", "url_options": { "data": "", "method": "GET" } }
     ]
    }
   ]
  },
  {
   "title": "Opensearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch | EA app E2E test results | ea-app-spa-e2e-test-results-pipeline",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OpenSearch | Photon Dev Metrics | photon_local_dev_metrics-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Elasticsearch | Apex Webstore | webstore-apex-e2e-test-results-pipeline",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OpenSearch | Banshee ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OpenSearch | Juno RATT | eax_juno_ratt-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "ts"
      }
     ]
    },
    {
     "title": "OpenSearch | Conductor | pipelines-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "OpenSearch | EA App SPA Pipeline | ea-app-pipeline-spa-metrics-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    },
    {
     "title": "Elasticsearch | VPC EAX Infrastructure Logs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "Log_ingestion_time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "*.*",
       "timeField": "Log_ingestion_time"
      }
     ]
    },
    {
     "title": "OpenSearch | EA App SPA Contributions | ea-app-contributions-spa-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticsearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elasticsearch | Juno Error Reporter Prod | jer-logs-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Elasticsearch | Juno Error Reporter Dev | jer-logs-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "*.*",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Elasticsearch | Juno RATT | eax_juno_ratt-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "timeField": "ts"
      }
     ]
    },
    {
     "title": "Elasticsearch | Juno RATT Dev | eax_juno_ratt-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "ts", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "*.*",
       "timeField": "ts"
      }
     ]
    },
    {
     "title": "Elasticsearch | EA app Rollout | gradual_rollout-*",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "start", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "*.*",
       "timeField": "start"
      }
     ]
    }
   ]
  },
  { "title": "CloudWatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CloudWatch | ea-origin-preprod | 264705682592",
   "type": "timeseries",
   "description": "IncomingBytes for CloudWatch | ea-origin-preprod | 264705682592",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | ea-ebisu | 889033191965",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | ea-layer-prod | 602543027410",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | ea-layer-preprod | 915535252088",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | eax-infra | 470694524926 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | eax-pubpltdev | 070665876018",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | eax-pubpltprod | 086000443580",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | gws-aws | 881577051366",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | kaboose-preprod | 980760520737",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | pulse-awstest | 523964902412",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | ym-test01 | 073838246296",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CloudWatch | ym-test02 | 647956898537",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "metricName": "IncomingBytes",
     "namespace": "AWS/Logs",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}